name: pre-commit

on:
  pull_request:
    paths-ignore: Hardware/**

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure changelog is updated
        uses: dangoslen/changelog-enforcer@v2
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Check pre-commit hooks
        uses: pre-commit/action@v2.0.0
      - name: Run platformio build
        uses: docker://kadaan/platformio_esp32:latest
        with:
          args: run
      

